spring:
  application.name: shopping-order-service
  datasource:
    url: 'jdbc:mysql://0.0.0.0:3306/db'
    username: user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update

feign.client.config.default:
  connectTimeout: 90000
  readTimeout: 90000
  loggerLevel: basic

eureka.client:
  register-with-eureka: false
  fetch-registry: false
  enabled: false

management:
  security.enabled: false
  git.info: full
  endpoint:
    health:
      show-details: always

spring.cache.type: none

hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 10000

security:
  basic.enabled: false
  require-ssl: false
  oauth2.resource.prefer-token-info: false

app:
  allowed:
    test: test2
    origins: http://localhost
  api:
    user.service.name: user-service
    product.service.name: product-service

product-service:
  ribbon:
    listOfServers: http://localhost:8081

user-service:
  ribbon:
    listOfServers: http://localhost:8083

