spring:
  application.name: shopping-common-lib

feign.client.config.default:
  connectTimeout: 90000
  readTimeout: 90000
  loggerLevel: basic

eureka.client:
  register-with-eureka: false
  fetch-registry: false
  enabled: false

management:
  security.enabled: false
  git.info: full
  endpoint:
    health:
      show-details: always

spring.cache.type: none

hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 10000

security:
  basic.enabled: false
  require-ssl: false
  oauth2.resource.prefer-token-info: false